### ISSUE TITLE
`when ~>` with no pattern?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-pattern-matching#101]
I see `when x ~> ... // always matches`, but what if I don't need the binding - can I omit it, and just do `when ~>?

**Comment by ljharb** [comment]
Makes sense - once `when` was cemented, would you see a reason not to pursue allowing the binding to be optional? (I'd compare it more to `catch` than function params, which soon allows you to omit the binding)

**Comment by ljharb** [comment]
Makes sense. Happy to either see this stay open as a "let's think about a no-binding solution", or close as answered.

**Comment by zkat** [comment]
I'm sure it'll come up again lol
