### ISSUE TITLE
GetIterator needs to only be called once, and all `next` values need to be reused if needed

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-pattern-matching#111]
(continuing from #99 and #102)

In:
```js
const arr = [1, 2, 3];
const iterator = arr.entries();
match(iterator) {
  when [[0, 1], [1, 1]] -> { } // should not match, and should call `.next()` twice
  when [[0, 1], [1, 2]] -> { } // should match, and should not call `.next()` additional times (and if it calls it twice here, it will be done after the first match)
}
```
`iterator` is already an iterator. Calling GetIterator on it will `return this`, so that part is fine - but if `.next()` is called to conceptually match the "first" item for my first "when" there in the example, it would need to match the second "when" as well.

In other words, all iterators are not reusable (including iterators the language provides built in, like `.entries()`/`.keys()`/`.values()`, and soon `.matchAll()`), so it's critical that the iterator is not exhausted prematurely.

**Comment by zkat** [comment]
Can you send me a PR with the rewording and fixed example you're looking for?
