### ISSUE TITLE
Minor critiques/notes on performance

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposal-pattern-matching#122]
Not an engine implementor (although I've been privately dabbling on some high-level implementation details for a theoretical low-memory 64-bit JS engine\*), but I just wanted to call some notes and critiques on the [performance consideration section](https://github.com/tc39/proposal-pattern-matching/blob/latest/CORE.md#-annex-b-performance-considerations).

> The general design of this `case` leans heavily towards hopefully allowing compiler-side optimizations. By minimizing runtime generation of matching logic, many when clauses can potentially be filtered according to PIC status (monomorphic/polymorphic/etc), as well as by Map/type. A sufficiently smart compiler should be able to reorder and omit branches and possibly reduce certain simpler match expressions to what a low-level `switch` might be.

In reality, an implementor might choose to first run a jump table based on the type map, and then proceed to check the individual slots' values. This eliminates 90% of the logic for actually checking types, since it's not unlike checking a tagged union, and it's pretty close to what actual functional compilers emit for pattern matching cases for discriminated unions.

Or at least that's my hope. I found it absurd that JSC was the only major implementation for about a year that thought to treat generators as a simple finite state machine, saving/restoring the program counter to suspend/resume the generator, making them almost zero-cost. Nobody else even tried as much as a `while`/`switch`, which was what Regenerator did - for a while, Regenerator's notoriously slow polyfill/transpiler output was *still* significantly faster than V8's (and I think SM's, too).

> The fact that variable matchers do not need to match against variables in surrounding scopes, and worry about their internal types, is probably also a big advantage -- variable bindings are simply typed the same as the corresponding value passed into `case` (again, optimized with PICs).

This simplifies the process, yes, but it only really simplifies building the control flow graph. Of course that'll have an impact on optimization, but it's not as much as you might expect - *every* `if`/`else` and loop has one of these at the end, so the plumbing already has to be there.

Control flow only really starts having a profound impact when you start to vectorize and parallelize, and most engines don't go *that* far in optimizing things. (I had to file a bug against V8 a few months ago so it'd even start using `memcpy`/`memmove` to optimize `Array.prototype.slice` for dense arrays.)

> Complex compounds might also cause issues (`&&`/`||`), but these can be optimized if all clauses have identical-typed matchers (`1 || 2 || 3 -> ...`).

If you use an initial type-checking jump table as I suggested above, you can avoid the indirection altogether here, so it barely costs anything to check compared to the rest. This is probably one of the easier cases, as long as you think of it as a series of individual cases pointing to identical blocks.

-----

\* I plan to write up many of these commonly missing, but highly useful optimizations in a blog post series eventually.

**Comment by zkat** [comment]
It doesn't seem like there's much further to discuss here, but thanks for the commentary!
