### ISSUE TITLE
Alternative value resolution syntax

### ISSUE THREAD

**Issue by JorisBlanken** [tc39/proposal-pattern-matching#138]
Hello,

In current examples patterns matched show a return statement, I feel it would be both more intuitive and more usefull if the pattern matching statement itselfs resolves a value.

Contrast the following.
Current:
```js
function factorial(n) {
    case (n) {
        when 0 -> return 1
        when n -> return n * factorial(n - 1)
    }
}
```
Syntax I propose:
```js
function factorial(n) {
    return case(n) {
        when 0 -> 1
        when n -> n * factorial(n - 1)
    }
}
```

Allows direct assignment to variables:
```js
let foo = true;
let bar = case (foo) {
    when true -> 'Yes'
    when false -> 'No'
}
console.log(bar); // 'Yes'
```

Allows intuitive integration into lambdas:
```js
const factorial = n => case (n) {
    when 0 -> 1
    when n -> n * factorial(n-1)
}
```

I would like to hear other's thoughts on this.

Thanks,
Joris

**Comment by FireyFly** [comment]
This is what #116 is about--I believe the proposal initially allowed both expressions and statements in the branches unconditionally, which caused problems with things like `break` and `continue`. The readme examples with `return` probably just aren't updated yet.
