### ISSUE TITLE
The current state of the proposal

### ISSUE THREAD

**Issue by SirMishaa** [tc39/proposal-pattern-matching#171]
Hello, 

This is an RFC that interests a lot of people, and it would be really appreciated. For this, I congratulate you in advance for the proposal.

Now, it is a matter of designating a champion and moving the proposal to step 2. Regarding this step / step preparation, have you found someone who wants to be champion? Or are you thinking of nominating yourself to move this one forward? 

I think there are some people who are willing to do this.

So I suggest you keep this issue open and try to move the proposal to step 2. If you don't want to be a champion for various reasons, let someone who does want to be a champion have the opportunity to be a champion.

This will give an idea of the progress of the proposal and a chance for this feature to be implemented. 

With kind regards.

**Comment by ljharb** [comment]
The champions are designated, and have been since it achieved stage 1 (it's a requirement to achieve it), although they've changed since then.

This issue will be closed, since we don't need a tracking issue at this time, and champions (who must be TC39 delegates) already exist.
