### ISSUE TITLE
Should we allow empty WhenClauseBody?

### ISSUE THREAD

**Issue by JLHwung** [tc39/proposal-pattern-matching#197]
The readme mentions that "The statement list [in the when clause, ] ... [is] with do expression semantics", since `do {}` is allowed as a shorter alternative for `void 0`, should we allow empty WhenClauseBody?

```js
match (res) {
  when ({ status: 500 }) {} // evaluates to undefined
  else {} // default is undefined
}
```

**Comment by ljharb** [comment]
if `do {}` is allowed, then both of these cases would absolutely be allowed, yes.
