### ISSUE TITLE
Proposal is missing GitHub pages rendering

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-pattern-matching#215]

**Comment by ljharb** [comment]
It's still stage 1; the spec isn't finalized or up to date so there's not really anything valuable to render yet.

**Comment by gibson042** [comment]
The repository includes [index.html](https://github.com/tc39/proposal-pattern-matching/blob/main/index.html), why shouldn't that be served?

**Comment by ljharb** [comment]
Because it doesn’t match the current proposal yet.
