### ISSUE TITLE
Allow `...` as a rest pattern in array patterns

### ISSUE THREAD

**Issue by tabatkins** [tc39/proposal-pattern-matching#234]
(Promoting this to a top-level discussion from the annals of <https://github.com/tc39/proposal-pattern-matching/issues/216#issuecomment-989047561>.)

Currently, you have two choices when you create an array pattern: either you require the matchable to have a specific length to match (like `[a, b, c]` requiring it to be exactly length 3), or you bind the "leftover" of the matchable to a name (like `[a, b, c, ...rest]`, which requires at least three items, and puts everything else into `rest`).

Implementing rest patterns like `...rest` requires us to exhaust the iterator we obtain from the matchable, so we can put all the items so obtained into a fresh Array. This, obviously, is incompatible with infinite iterators, which'll just hang the script at this point.

Even implementing exact-length array patterns, tho, means finite one-shot iterators are treated *slightly* strangely. To match an iterator against `[a, b, c]`, we have to pull *four* items from it, to verify that the fourth attempt fails and it does indeed only contain three items. 

And even if an iterator is theoretically finite, its items might be expensive to calculate, so using a rest pattern just to relax the length requirement might trigger excessive unwanted computation.

I suggest we fix both of these by allowing a rest pattern without an ident, spelled `...`, to be used at the end of an array pattern, to indicate that the length requirement is relaxed and the rest of the iterator will be left unchanged. That is, `[a, b, c, ...]` will pull exactly three items from the iterator, no more, and succeed so long as the three patterns match. Finite iterators will only pull items necessary for matching, and infinite iterators will actually be possible to use.

(To do the old standby `(head : tail)` pattern where the tail is lazy, you'd write it as `when ([head, ...] & tail)`. `tail` will bind the matchable itself, which in this context is an iterator that's had one item pulled from it by the array pattern. This doesn't generalize to work correctly on iterables, unfortunately, but that dichotomy is something we're accepting in other aspects already.)

----

The obvious objection to this is that it's not a syntax currently allowed in destructuring, and we try to keep array/object patterns close to destructuring in syntax (identical, when possible). However, this is because destructuring uses this semantic *by default*; any time you write `[a, b] = arr;` you're trying to pull two items from the iterator, but are fine if it has more items in it (and even if it has *less* items in it, binding the leftovers to `undefined`). We don't have the capability to do a strict length match in destructuring unless we allow especially weird hacky stuff, like `{length: 2, "0": a, "1": b} = arr;`, which in practice is nonexistent. (I presume tuple destructuring might eventually do this, tho. It's the default in Python, which *only* has tuple destructuring.)

However, the length check is an assumed and important part of pattern matching, which most (all?) extant pattern-matching language features use by default when relevant. The ability to write `when ([a]) ...; when ([a, b]) ...;` and have it work as expected is *very* important, so this divergence is unavoidable. We just fundamentally have an additional state the system can be in in pattern matching that's not shared with destructuring, so we need to address it with syntax that's not in destructuring.

**Comment by theScottyJam** [comment]
Thanks @tabatkins for the feedback. I created another issue (#235) to discuss it further.
