### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by limeblack** [tc39/proposal-pattern-matching#26]
Has this been considered or some variant so it supports multiple lines.

```
match( obj ) {
  case {x, y}:
    ...
  break;
}
```

**Comment by ljharb** [comment]
then what happens if you forget the `break`? Seems just as bad as `switch` that way :-/

**Comment by limeblack** [comment]
@ljharb  what do you propose for multiline support?  `{}`?

**Comment by bterlson** [comment]
Current proposal uses async-function-like legs so starting with `{` starts a block. The design alternatives section goes over the various options here - file an issue if you think the content there is lacking/wrong/etc!

**Comment by limeblack** [comment]
thanks!
