### ISSUE TITLE
Rest spec work

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-pattern-matching#260]
- [ ] Butil-in matchers (need a list for them)
- [ ] `Symbol.matcher`
- [ ] Early errors (need a list for them)

**Comment by ljharb** [comment]
I would expect every builtin constructor to have a matcher that checks for the presence of the internal slot its instances are expected to have.

**Comment by Jack-Works** [comment]
> I would expect every builtin constructor to have a matcher that checks for the presence of the internal slot its instances are expected to have.

For example, does TypeError has its own internal slot so we can distinguish it from Error?

**Comment by ljharb** [comment]
Good question, but yes, I would expect it to validate that it's a TypeError and not another kind of error object.

**Comment by Jack-Works** [comment]
mostly done.
