### ISSUE TITLE
Stage 2 and `when`

### ISSUE THREAD

**Issue by johnknoop** [tc39/proposal-pattern-matching#286]
Hi!

Two questions:

- Pattern matching was proposed for stage 2 earlier this year, but I haven't been able to find any info on the outcome. Is it still in stage 1 and if so how come?
- The `when` keyword really adds verbosity compared to something like C# or F# pattern matching. Have you exhausted all possibilities to get rid of it?

Thanks

**Comment by ljharb** [comment]
It was not proposed for stage 2; we received some last-minute feedback and withdrew it from consideration.

The `when` keyword, and its verbosity, has been discussed extensively and the majority of us consider it both desirable and necessary.
