### ISSUE TITLE
Spec: Use Map instead of WeakMap

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-pattern-matching#290]
since we're redesign this proposal, we can do it in the next rewrite

**Comment by ljharb** [comment]
Wait, why this change? We want things to be held weakly, no?

**Comment by bathos** [comment]
Am I correct to guess the difference would become observable only if yielding within a match?

**Comment by Jack-Works** [comment]
> Wait, why this change? We want things to be held weakly, no?

It was the decision made from the previous discussion. It is also not observable (Map or WeakMap) anyway, because it's impossible (if we don't have a bug in the spec) to leak the cache object to the userland.

I cannot recall the reason why someone want Map not WeakMap, maybe it's related to GC stuff.

**Comment by Jack-Works** [comment]
> Am I correct to guess the difference would become observable only if yielding within a match?

Oh, maybe it _is_ observable I'm not sure, if `await` or `yield` happened inside a match, but in this case, I think it would be better to keep things strongly held, otherwise, the match might behave in a strange way.
