### ISSUE TITLE
README and rendered spec are inconsistent about Symbol.matcher vs. Symbol.customMatcher

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-pattern-matching#318]
(_<em>originally posted by @gibson042 in https://github.com/tc39/proposal-pattern-matching/pull/293#discussion_r1311839210</em>)

README.md mentions `Symbol.customMatcher` while the spec defines `Symbol.matcher`.

**Comment by tabatkins** [comment]
This is fixed in the [spec PR](https://github.com/tc39/proposal-pattern-matching/pull/295) (we're using `customMatcher`)
