### ISSUE TITLE
README implies that regular expression literals are privileged over other instances

### ISSUE THREAD

**Issue by gibson042** [tc39/proposal-pattern-matching#319]
(<em>originally posted by @gibson042 in https://github.com/tc39/proposal-pattern-matching/pull/293#discussion_r1311844389</em>)

https://github.com/tc39/proposal-pattern-matching#regex-patterns
> > A regex pattern is a regex literal, representing a test that the subject, when stringified, successfully matches the regex.
> 
> Is this privileging literals in such a way that `when /.../` can act differently than `when re` after `re = /.../` in an environment where primordials have been subject to arbitrary manipulation?

It _does_ include clarifying text:
> (Technically, this just invokes the <code>RegExp.prototype[Symbol.customMatcher]</code> method; that is, <code>x is /foo/;</code> and <code>let re = /foo/; x is re;</code> are identical in behavior wrt built-in fiddling.)

...but the initial sentence is still misleading.

The section's "**Examples**" block is also empty.

**Comment by tabatkins** [comment]
Given that the clarifying sentence is literally the next text in the README, I think that's sufficient for now?

(And yes, examples need to be filled in for multiple sections.)
