### ISSUE TITLE
Questions about match expression

### ISSUE THREAD

**Issue by NagayamaToshiaki** [tc39/proposal-pattern-matching#328]
I have 2 questions about match expression.

1. There is no notion if the semicolon in the default arm is required. I thought it's also required because those of match arms are so. Is it right? I think the necessity of semicolon should be explicitly written.
2. According to the document, "If there is no default arm, the match expression throws a `TypeError`." So you mean default arm is *always* required? If so, why isn't it the parse error?

**Comment by ljharb** [comment]
It’s required, like every other semicolon in the language.

No, if your match is exhaustive - if it never hits the fallback - there won’t be a runtime error.
