### ISSUE TITLE
Disallow SequenceExpression consequents

### ISSUE THREAD

**Issue by rattrayalex** [tc39/proposal-pattern-matching#33]
I believe you will need to disallow `SequenceExpression` consequents: 

```
match (foo) {
  1: a, 
  2: b
}
```

the above would parse as a SequenceExpression of `a, 2`, and then error at the colon. 

I assume you were aware of this, but I didn't see it specified in the grammar. 

(This is commonly accomplished in the babylon codebase, for example, by calling `parseMaybeAssign` instead of `parseExpression`)

**Comment by Jamesernator** [comment]
This happens pretty much everywhere there could be commas array literals, object literals, variable declarations, etc.

Most places in the spec use `AssignmentExpression` instead of `Expression` for this sort've reason, so I'd use that.
