### ISSUE TITLE
References and prior literature

### ISSUE THREAD

**Issue by Xananax** [tc39/proposal-pattern-matching#85]
I thought it could be useful to reference similar implementations in other languages, or generic discussions about the construct.

I'll start with this discussion for the implementation of `match` in Godot
https://github.com/godotengine/godot/issues/6593

It's not terribly useful due to the pythonesque nature of GDScript, but there's some points in there which will undoubtedly come up. Can be interesting to some degree

**Comment by zkat** [comment]
Unless there's something more actionable here than just generally adding more references, I'm gonna go ahead and close this.
