### ISSUE TITLE
Match instances

### ISSUE THREAD

**Issue by goodmind** [tc39/proposal-pattern-matching#87]
How this proposal addresses matching class instances and `Symbol.hasInstance`?

**Comment by tabatkins** [comment]
Handled by the (now separated from the main proposal) [tagged collection literals proposal](https://github.com/zkat/proposal-collection-literals).

**Comment by zkat** [comment]
As @tabatkins says, this particular feature is something I'm considering out of scope for this part of the proposal. You will still be able to do this manually by using `if (...)` guards.
