### ISSUE TITLE
Nucleus for matching

### ISSUE THREAD

**Issue by martinheidegger** [tc39/proposal-pattern-matching#95]
`match` is an interesting concept but I think it might make sense to have one single matching operation separately available. Can a matcher be an Operation, an Until or a class maybe? Similar to RegExp?

```javascript
class Match {
  constructor (rule) {
     if (rule === null) {
        this.rule = {[Match.field]: value => value === null}
     } else if (rule === undefined) {
        this.rule = {[Match.field]: value => value === undefined}
     // etc.
     } else {
        this.rule = rule
     }
  }
  test(value) {
     return this.rule[Match.field](value) ? true : false
  }
}
Match.field = Symbol()
Match.test = (rule, value) => (new Match(rule)).test(value)
Object.prototype[Match.field] = (value) => {
  // general matching logic...
}
```

This way it would be easier to explain the logic behind what makes `match(..)` work?

**Comment by zkat** [comment]
The core matching proposal limits matching logic to corresponding logic for the existing destructuring assignment/binding syntax, as a minimum initial goal. Further, arbitrary pattern matching and the related API is covered by [the tagged collection literals proposal](https://github.com/zkat/proposal-collection-literals), linked from the original one. Please refer to that to answer your question, and keep discussion about the specifics of that API to that separate proposal.
